### ISSUE TITLE
Stage1{线索} [Bug]

### ISSUE THREAD

**Issue by murez** [ShanghaitechGeekPie/GeekPie2020Games#1]
stage1的网页线索可以通过查看js找出
在访问[censored]的时候，可以审查元素
在
```
[censored]
```
中我们可以发现如下代码
```
[censored]
```
所以可以直接访问[censored]进行游戏

另外还可以通过[censored]获得关卡提示

**Comment by YzyParry** [comment]
臣附议，其实根本不知道[censored]是什么意思

**Comment by eEhyQx** [comment]
"这是游戏的一部分"

**Comment by LEAFERx** [comment]
谢谢你的提交 情况属实 目前对敏感信息做删除处理 请见谅
