### ISSUE TITLE
[Bug]关于通关人数统计的bug

### ISSUE THREAD

**Issue by Nyovelt** [ShanghaitechGeekPie/GeekPie2020Games#10]
*我已经确认该 Bug 仅仅影响用户体验，与安全无关。与安全相关的 Bug 或漏洞请直接发送邮件至 leaferx@outlook.com*

**Bug 描述**
通关人数只是统计了有多少人大于等于1200的情况，而没有考虑有bonus。而且似乎除非更改前后端否则无法修复，或者随着时间的推移，它会自动修复。

**重现方法**
打开首页

**预期的行为**

**截图**

**Desktop (please complete the following information):**
 - 操作系统： Windows 10 1909
 - 浏览器： FireFox
 - 浏览器版本（可选）： 

**其他你认为重要的信息**

**Comment by eEhyQx** [comment]
其实考虑到了，但是想到只有xht一个人有额外分，所以忽略了。
