### ISSUE TITLE
bug？）

### ISSUE THREAD

**Issue by patrickstar111** [ShanghaitechGeekPie/GeekPie2020Games#4]
如果使用网页审查元素，当我在task1的时候就可以在webpack中的src的tasks中查看到所有五个任务的内容xxxx（

**Comment by LEAFERx** [comment]
由于vue和前端的限制这么做的确可行，但是对活动本身没有影响，因为所有的解题进度都会被检查，玩家不能跳过题目作答。目前我已经删除.map文件正在等待cdn刷新。

**Comment by eEhyQx** [comment]
“这是游戏的一部分”
