### ISSUE TITLE
Stage3 task3 task4的验证bug

### ISSUE THREAD

**Issue by YzyParry** [ShanghaitechGeekPie/GeekPie2020Games#7]
**Bug 描述**
在Stage3的task3、task4中，不输入任何答案直接按【submit】，网页会通知通过，并进入下一个task4或结尾祝贺页面，但并不会认定为完成该题目，获得相应的分数

**重现方法**
如上所述

**预期的行为**
和task1一致，指出为【无效/错误的submit】

**Comment by eEhyQx** [comment]
fixed

**Comment by YzyParry** [comment]
似乎没有修复，刚才测试还是有同样的问题
