### ISSUE TITLE
bugs]关于stage3分数reset问题

### ISSUE THREAD

**Issue by patrickstar111** [ShanghaitechGeekPie/GeekPie2020Games#9]
**对象**
(Stage3 )
当stage3通过task2后进行task3和task4的解密时，如果重新进入界面并且没有再次打开神秘网站，会导致task2无法通过，导致分数reset（-200）（我有个朋友由于这个原因，在完成所有stage后在task2掉分了）

**Comment by LEAFERx** [comment]
目前后端已加入检查，对已完成的 task 服务器数据不会再修改。为了兼容前端，服务器在检测到进度不符合目前 task 时仍然会返回 success。
